version: '3.4'

networks:
  traces-network:
    name: traces/feature-v1
    external: true
  monitoring:
    driver: bridge


services:

  otel-collector:
    image: otel/opentelemetry-collector:0.61.0
    networks:
      - traces-network
    command: [ "--config=/etc/otel-collector.yaml" ]
    env_file:
      - telemetry.env
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   expose:
  #     - 9100
  #   networks:
  #     - monitoring

  tempo:
    image: grafana/tempo:latest
    networks:
      - traces-network
    command: [ "-config.file=/etc/tempo.yaml" ]
    env_file:
      - telemetry.env
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200"  # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http

  prometheus:
    image: prom/prometheus:latest
    networks:
      - traces-network
      - monitoring
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    env_file:
      - telemetry.env
    environment:
      - TARGET_URL='node-app:5900'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - traces-network
    env_file:
      - telemetry.env
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    # depends_on:
    #   - tempo
    ports:
      - "3000:3000"

