{
 "title": "admin-api-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } },
   { "name": "blockchain", "label": "blockchain", "query": { "query": "label_values(blockchain)" } }
  ]
 },
 "panels": [
  {
   "title": "total-http-requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(response_time_duration_seconds_count{status_code=\"200\"})",
     "legendFormat": "success-calls"
    },
    {
     "expr": "sum(response_time_duration_seconds_count{status_code!=\"200\"})",
     "legendFormat": "faliure-calls"
    }
   ]
  },
  {
   "title": "http-response-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(async_funtions_response_time_duration_seconds_sum{instance=\"app:5900\",blockchain=\"$blockchain\"}[1m]) / rate(async_funtions_response_time_duration_seconds_count{instance=\"app:5900\",blockchain=\"$blockchain\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http-requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ceil(rate(async_funtions_response_time_duration_seconds_count{instance=\"app:5900\", blockchain=\"$blockchain\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http-error-status-codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ceil(rate(async_funtions_response_time_duration_seconds_count{success=\"false\", blockchain=\"$blockchain\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http-faliure-calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ceil(rate(async_funtions_response_time_duration_seconds_count{success!=\"true\", blockchain=\"$blockchain\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"app:5900\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"app:5900\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"app:5900\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"app:5900\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"app:5900\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance|app:5900\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"app:5900\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"app:5900\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"app:5900\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  }
 ]
}