{
 "title": "reservoir-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "total-http-requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reservoir_requets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "reseroir-calls-success",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "async_funtions_response_time_duration_seconds_count{status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reservoir-calls-failing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "async_funtions_response_time_duration_seconds_count{status_code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reservoir-calls-success-rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ceil(rate(async_funtions_response_time_duration_seconds_count{instance=\"node-app:5900\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http-response-time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "\r\nsum(rate(rest_response_time_duration_seconds_sum{route=\"/history/getHistory\"}[5m])) / sum(rate(rest_response_time_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http-error-status-codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "ceil(rate(rest_response_time_duration_seconds_count{route=\"/history/getHistory\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http-requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "ceil(rate(reservoir_requets{instance=\"node-app:5900\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trace-metrics",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "limit": 20, "serviceName": "reservoir-server", "spanName": "reservoir-span" }
   ]
  },
  {
   "title": "search-by-trace-id",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "limit": 20,
     "query": "12b7c6c1eb8aa12245ef43795fb781e3",
     "serviceName": "reservoir-server",
     "spanName": "reservoir-span"
    }
   ]
  }
 ]
}