{
 "title": "rarible-runner-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "assets added",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asset_count_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "collections_added",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collection_count_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rarible-api-calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(fetch_asset_sum{instance=\"$instance\"}[1m])) / sum(rate(fetch_asset_count[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(fetch_collection_sum{instance=\"$instance\"}[1m])) / sum(rate(fetch_collection_count[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(fetch_owner_sum{instance=\"$instance\"}[1m])) / sum(rate(fetch_owner_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "database saving time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(create_asset_sum{job=\"node-app-configs\"}[1m])) / sum(rate(create_asset_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(create_collection_sum{job=\"node-app-configs\"}[1m])) / sum(rate(create_collection_count{instance=\"rarible_runner_service:8000\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(create_traits_sum{job=\"node-app-configs\"}[1m])) / sum(rate(create_traits_count{instance=\"rarible_runner_service:8000\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(create_owner_sum{job=\"node-app-configs\"}[1m])) / sum(rate(create_owner_count{instance=\"rarible_runner_service:8000\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(create_creators_sum{job=\"node-app-configs\"}[1m])) / sum(rate(create_creators_count{instance=\"rarible_runner_service:8000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "failed-to-save-In-db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "rate(create_asset_count{http_status!=\"200\",instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(create_collection_count{http_status!=\"200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "failed fetch calls to rarible",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(fetch_asset_count{http_status!=\"200\",instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(fetch_collection_count{http_status!=\"200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"node-app-configs\",instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"node-app-configs\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"node-app-configs\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}